/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg1st.quarter.exam;

import java.lang.reflect.Method;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BRIONES_CpE121
 */
public class PaymentFront extends javax.swing.JFrame {

    DefaultTableModel cart;
    String deliveryText;
    double Ftotal = 0.00;

    public PaymentFront() {
        initComponents();

    }

    public PaymentFront(DefaultTableModel model) {
        initComponents();
        cart = model;
        CartList.setModel(cart);
    }

    public void CheckoutTotal(double total) {
        Ftotal = total;
        Total.setText(String.valueOf("$ " + Ftotal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TransitMode = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        CartList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        PaymentMode = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Delivery = new javax.swing.JRadioButton();
        Pickup = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CartList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Product", "Price", "Quantity", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CartList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 19, 394, 380));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Pay Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 54));

        PaymentMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card", "Cash", "Gcash", "PayMaya" }));
        PaymentMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentModeActionPerformed(evt);
            }
        });
        getContentPane().add(PaymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 202, -1));

        jLabel1.setText("Payment Method");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 187, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total");

        Total.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total.setText("$ 0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 90, 80));

        TransitMode.add(Delivery);
        Delivery.setText("Delivery");
        Delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryActionPerformed(evt);
            }
        });
        getContentPane().add(Delivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, -1));

        TransitMode.add(Pickup);
        Pickup.setText("Pick up");
        Pickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickupActionPerformed(evt);
            }
        });
        getContentPane().add(Pickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Transit Mode");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String PaymMode = (String) PaymentMode.getSelectedItem(); // Get selected item

        if (TransitMode.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Please select a transit mode before checkout.");
            return; // Stop execution
        }

        if (PaymMode.equals("Card")) {

            if (Delivery.isSelected()) {
                deliveryText = "Delivery";
            } else if (Pickup.isSelected()) {
                deliveryText = "Pick Up";

            }
            JOptionPane.showMessageDialog(null, "Thank you for Shopping with Us. Here's your card. The delivery method is " + deliveryText);
        } else if (PaymMode.equals("Cash")) {

            if (Delivery.isSelected()) {
                deliveryText = "Delivery";
            } else if (Pickup.isSelected()) {
                deliveryText = "Pick Up";
            }
            JOptionPane.showMessageDialog(null, "Thank you for Shopping with Us.The delivery method is " + deliveryText);
        } else if (PaymMode.equals("Gcash")) {

            if (Delivery.isSelected()) {
                deliveryText = "Delivery";
            } else if (Pickup.isSelected()) {
                deliveryText = "Pick Up";

            }
            JOptionPane.showMessageDialog(null, "Thank you for Shopping with Us. Gcash payment is completed. The delivery method is " + deliveryText);
        } else if (PaymMode.equals("PayMaya")) {

            if (Delivery.isSelected()) {
                deliveryText = "Delivery";
            } else if (Pickup.isSelected()) {
                deliveryText = "Pick Up";

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a valid payment method.");
        }

        this.dispose();
        StoreFront open = new StoreFront();
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PaymentModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentModeActionPerformed

    }//GEN-LAST:event_PaymentModeActionPerformed

    private void DeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryActionPerformed

    }//GEN-LAST:event_DeliveryActionPerformed

    private void PickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PickupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentFront().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CartList;
    private javax.swing.JRadioButton Delivery;
    private javax.swing.JComboBox<String> PaymentMode;
    private javax.swing.JRadioButton Pickup;
    private javax.swing.JLabel Total;
    private javax.swing.ButtonGroup TransitMode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
