package pkg1st.quarter.exam;

import java.beans.Visibility;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;

/**
 * b
 *
 * @author BRIONES_CpE121
 */
public class StoreFront extends javax.swing.JFrame {

    DefaultTableModel oldmodel;
    DefaultTableModel newmodel;
    private String ProductName;
    private String Id;
    private String Price;
    private double pricing;
    private String quantity;
    private double total = 0.00;
    private double subtotal = 0.00;
    private String Ftotal = "";
    private double quanty;

    /**
     * Creates new form StoreFront
     */
    public StoreFront() {
        this.total = 00.00;
        initComponents();
        oldmodel = (DefaultTableModel) Cart.getModel();
        oldmodel.setRowCount(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IdFrame = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        banana = new javax.swing.JButton();
        Melon = new javax.swing.JButton();
        Sitaw = new javax.swing.JButton();
        Isda = new javax.swing.JButton();
        Karne = new javax.swing.JButton();
        Silopin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BananaValue = new javax.swing.JLabel();
        MelonValue = new javax.swing.JLabel();
        SitawValue = new javax.swing.JLabel();
        IsdaValue = new javax.swing.JLabel();
        KarneValue = new javax.swing.JLabel();
        SilopinValue = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        NewBanana = new javax.swing.JLabel();
        NewMelon = new javax.swing.JLabel();
        NewSitaw = new javax.swing.JLabel();
        NewIsda = new javax.swing.JLabel();
        Newkarne = new javax.swing.JLabel();
        NewSilopin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cart = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Quantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Yohan Store");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 20, 260, 60));

        IdFrame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jLabel2.setAlignmentX(0.1F);

        banana.setText("1");
        banana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bananaActionPerformed(evt);
            }
        });

        Melon.setText("2");
        Melon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MelonActionPerformed(evt);
            }
        });

        Sitaw.setText("3");
        Sitaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SitawActionPerformed(evt);
            }
        });

        Isda.setText("4");
        Isda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsdaActionPerformed(evt);
            }
        });

        Karne.setText("5");
        Karne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KarneActionPerformed(evt);
            }
        });

        Silopin.setText("6");
        Silopin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilopinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IdFrameLayout = new javax.swing.GroupLayout(IdFrame);
        IdFrame.setLayout(IdFrameLayout);
        IdFrameLayout.setHorizontalGroup(
            IdFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IdFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(banana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Melon, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(Sitaw, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(Isda, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(Karne, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(Silopin, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );
        IdFrameLayout.setVerticalGroup(
            IdFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IdFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(banana)
                .addGap(18, 18, 18)
                .addComponent(Melon)
                .addGap(18, 18, 18)
                .addComponent(Sitaw)
                .addGap(18, 18, 18)
                .addComponent(Isda)
                .addGap(18, 18, 18)
                .addComponent(Karne)
                .addGap(18, 18, 18)
                .addComponent(Silopin)
                .addGap(360, 360, 360))
        );

        getContentPane().add(IdFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 300));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Price");

        BananaValue.setText("1.5");

        MelonValue.setText("5");

        SitawValue.setText("0.25");

        IsdaValue.setText("15");

        KarneValue.setText("10");

        SilopinValue.setText("0.50");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BananaValue)
                    .addComponent(MelonValue)
                    .addComponent(SitawValue)
                    .addComponent(IsdaValue)
                    .addComponent(KarneValue)
                    .addComponent(SilopinValue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BananaValue)
                .addGap(27, 27, 27)
                .addComponent(MelonValue)
                .addGap(26, 26, 26)
                .addComponent(SitawValue)
                .addGap(26, 26, 26)
                .addComponent(IsdaValue)
                .addGap(26, 26, 26)
                .addComponent(KarneValue)
                .addGap(26, 26, 26)
                .addComponent(SilopinValue)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, 300));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NewBanana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewBanana.setText("Banana");
        NewBanana.setMaximumSize(new java.awt.Dimension(23, 23));
        NewBanana.setMinimumSize(new java.awt.Dimension(23, 23));

        NewMelon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewMelon.setText("Melon");
        NewMelon.setMaximumSize(new java.awt.Dimension(23, 23));
        NewMelon.setMinimumSize(new java.awt.Dimension(23, 23));

        NewSitaw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewSitaw.setText("Sitaw");
        NewSitaw.setMaximumSize(new java.awt.Dimension(23, 23));
        NewSitaw.setMinimumSize(new java.awt.Dimension(23, 23));

        NewIsda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewIsda.setText("Isda");
        NewIsda.setMaximumSize(new java.awt.Dimension(23, 23));
        NewIsda.setMinimumSize(new java.awt.Dimension(23, 23));

        Newkarne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Newkarne.setText("Karne");
        Newkarne.setMaximumSize(new java.awt.Dimension(23, 23));
        Newkarne.setMinimumSize(new java.awt.Dimension(23, 23));

        NewSilopin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewSilopin.setText("Silopin");
        NewSilopin.setMaximumSize(new java.awt.Dimension(23, 23));
        NewSilopin.setMinimumSize(new java.awt.Dimension(23, 23));

        jLabel4.setBackground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Names");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewBanana, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewMelon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSitaw, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewIsda, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Newkarne, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewSilopin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(NewBanana, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewMelon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewSitaw, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewIsda, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Newkarne, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewSilopin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 300));

        jButton1.setText("Proceed to checkout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Product", "Price", "Quantity", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Cart);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 90, 380, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Quantity.setText("1");
        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantity");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 40));

        Body.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TOTAL");

        Total.setText("$0.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(Total)
                .addGap(27, 27, 27))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Total)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cart");

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addContainerGap(522, Short.MAX_VALUE)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void SilopinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilopinActionPerformed
        String quant = Quantity.getText();
        int Validation = Integer.parseInt(quant);
        if (Validation >= 1) {
            ProductName = NewSilopin.getText();
            Id = "6";
            Price = SilopinValue.getText();
            quantity = Quantity.getText();

            Quantity.setText("1");
            pricing = Double.parseDouble(Price);
            quanty = Double.parseDouble(quant);
            total += pricing * quanty;
            Ftotal = String.valueOf(total);
            subtotal = pricing * quanty;
            oldmodel.addRow(new Object[]{Id, ProductName, "$" + Price, quantity, +subtotal});
            Total.setText(String.valueOf("$" + total));

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }


    }//GEN-LAST:event_SilopinActionPerformed

    private void KarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KarneActionPerformed
        String quant = Quantity.getText();
        int Validation = Integer.parseInt(quant);
        if (Validation >= 1) {
            ProductName = Newkarne.getText();
            Id = "5";
            Price = KarneValue.getText();
            quantity = Quantity.getText();
            Quantity.setText("1");
            pricing = Double.parseDouble(Price);
            quanty = Double.parseDouble(quant);
            total += pricing * quanty;
            Ftotal = String.valueOf(total);
            subtotal = pricing * quanty;
            oldmodel.addRow(new Object[]{Id, ProductName, "$" + Price, quantity, +subtotal});
            Total.setText(String.valueOf("$" + total));
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");

        }

    }//GEN-LAST:event_KarneActionPerformed

    private void IsdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsdaActionPerformed
        String quant = Quantity.getText();
        int Validation = Integer.parseInt(quant);
        if (Validation >= 1) {
            ProductName = NewIsda.getText();
            Id = "4";
            Price = IsdaValue.getText();
            quantity = Quantity.getText();
            Quantity.setText("1");
            pricing = Double.parseDouble(Price);
            quanty = Double.parseDouble(quant);
            total += pricing * quanty;
            Ftotal = String.valueOf(total);
            subtotal = pricing * quanty;
            oldmodel.addRow(new Object[]{Id, ProductName, "$" + Price, quantity, +subtotal});
            Total.setText(String.valueOf("$" + total));
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }

    }//GEN-LAST:event_IsdaActionPerformed

    private void SitawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SitawActionPerformed
        String quant = Quantity.getText();
        int Validation = Integer.parseInt(quant);
        if (Validation >= 1) {
            ProductName = NewSitaw.getText();
            Id = "3";
            Price = SitawValue.getText();
            quantity = Quantity.getText();

            Quantity.setText("1");
            pricing = Double.parseDouble(Price);
            quanty = Double.parseDouble(quant);
            total += pricing * quanty;
            Ftotal = String.valueOf(total);
            subtotal = pricing * quanty;
            oldmodel.addRow(new Object[]{Id, ProductName, "$" + Price, quantity, +subtotal});
            Total.setText(String.valueOf("$" + total));

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }

    }//GEN-LAST:event_SitawActionPerformed

    private void MelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MelonActionPerformed
        String quant = Quantity.getText();
        int Validation = Integer.parseInt(quant);
        if (Validation >= 1) {
            ProductName = NewMelon.getText();
            Id = "2";
            Price = MelonValue.getText();
            quantity = Quantity.getText();
            Quantity.setText("1");
            pricing = Double.parseDouble(Price);
            quanty = Double.parseDouble(quant);
            total += pricing * quanty;
            Ftotal = String.valueOf(total);
            subtotal = pricing * quanty;
            oldmodel.addRow(new Object[]{Id, ProductName, "$" + Price, quantity, +subtotal});

            Total.setText(String.valueOf("$" + total));
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }

    }//GEN-LAST:event_MelonActionPerformed

    private void bananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bananaActionPerformed

        String quant = Quantity.getText();
        int Validation = Integer.parseInt(quant);
        if (Validation >= 1) {
            ProductName = NewBanana.getText();
            Id = "1";
            Price = BananaValue.getText();
            quantity = Quantity.getText();
            pricing = Double.parseDouble(Price);
            quanty = Double.parseDouble(quant);
            total += pricing * quanty;
            Ftotal = String.valueOf(total);
            subtotal = pricing * quanty;
            oldmodel.addRow(new Object[]{Id, ProductName, "$" + Price, quantity, +subtotal});
            Total.setText(String.valueOf("$" + total));

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }
    }//GEN-LAST:event_bananaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel oldmodel = (DefaultTableModel) Cart.getModel();
        DefaultTableModel newmodel = new DefaultTableModel();
        for (int i = 0; i < oldmodel.getColumnCount(); i++) {
            newmodel.addColumn(oldmodel.getColumnName(i));
        }

        // Copy rows
        for (int i = 0; i < oldmodel.getRowCount(); i++) {
            Vector row = (Vector) oldmodel.getDataVector().get(i);
            newmodel.addRow(row.toArray()); // Convert to Object[]
        }

        // Open PaymentFront and pass the new model
        PaymentFront payment = new PaymentFront(newmodel);
        payment.setVisible(true);
        this.dispose();
        payment.CheckoutTotal(total);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed

        String Validate = Quantity.getText();
        int value = Integer.parseInt(Validate);
        if (value <= 0) {
            JOptionPane.showMessageDialog(null, "Invalid Quantity!");
            Quantity.setText("1");
        }


    }//GEN-LAST:event_QuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreFront().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BananaValue;
    private javax.swing.JPanel Body;
    private javax.swing.JTable Cart;
    private javax.swing.JPanel IdFrame;
    private javax.swing.JButton Isda;
    private javax.swing.JLabel IsdaValue;
    private javax.swing.JButton Karne;
    private javax.swing.JLabel KarneValue;
    private javax.swing.JButton Melon;
    private javax.swing.JLabel MelonValue;
    private javax.swing.JLabel NewBanana;
    private javax.swing.JLabel NewIsda;
    private javax.swing.JLabel NewMelon;
    private javax.swing.JLabel NewSilopin;
    private javax.swing.JLabel NewSitaw;
    private javax.swing.JLabel Newkarne;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton Silopin;
    private javax.swing.JLabel SilopinValue;
    private javax.swing.JButton Sitaw;
    private javax.swing.JLabel SitawValue;
    private javax.swing.JLabel Total;
    private javax.swing.JButton banana;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
