/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cpe121.briones.finalproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yuanb
 */
public class UserFront extends javax.swing.JFrame {

    private String name = "";
    private String Accountnumb = "";
    private double balance = 00.00;
    private String Sbal = Double.toString(balance);

    public UserFront() {
        initComponents();
        
    }
    public UserFront(String names){
        initComponents();
        
        this.Accountnumb = names;
        Search();
        MainName.setText(name);
        MainAcc.setText(Accountnumb);
        MainBal.setText(Sbal);
        
    }

    public void Search() {
        DB_connection.init();
        Connection c = DB_connection.getConnection();
        try {
            PreparedStatement ps = c.prepareStatement("SELECT * FROM accounts where accountnumber = '" + Accountnumb + "';");
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                name = rs.getString("Name");
                Sbal = rs.getString("Balance");
            }
        } catch (SQLException ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UserName = new javax.swing.JLabel();
        UserNumber = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MainBal = new javax.swing.JLabel();
        MainName = new javax.swing.JLabel();
        MainAcc = new javax.swing.JLabel();
        UserSend = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        UserPayBill = new javax.swing.JButton();
        UserLoan = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("E-BANK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 25, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName.setText("Name");
        jPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        UserNumber.setText("Account Number");
        jPanel1.add(UserNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, -1));

        jLabel2.setText("Balance");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        MainBal.setText("Amount");
        jPanel1.add(MainBal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 250, -1));

        MainName.setText("ex.yohan");
        jPanel1.add(MainName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 260, -1));

        MainAcc.setText("*****");
        jPanel1.add(MainAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 340, 100));

        UserSend.setText("Send");
        UserSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSendActionPerformed(evt);
            }
        });
        getContentPane().add(UserSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jButton1.setText("Transactions");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 130, -1));

        UserPayBill.setText("Pay Loan");
        UserPayBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPayBillActionPerformed(evt);
            }
        });
        getContentPane().add(UserPayBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        UserLoan.setText("Loan");
        UserLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLoanActionPerformed(evt);
            }
        });
        getContentPane().add(UserLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jButton5.setText("Change Password");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSendActionPerformed
        SendForm open  = new SendForm(Accountnumb);
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserSendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Transactions transfer = new Transactions(Accountnumb);
        transfer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UserLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLoanActionPerformed
        LoanForm open = new LoanForm(Accountnumb, name);
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserLoanActionPerformed

    private void UserPayBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPayBillActionPerformed
        PayLoan open = new PayLoan(Accountnumb, name);
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserPayBillActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       LogIn open = new LogIn();
       open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Changepass open = new Changepass(Accountnumb);
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFront().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainAcc;
    private javax.swing.JLabel MainBal;
    private javax.swing.JLabel MainName;
    private javax.swing.JButton UserLoan;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel UserNumber;
    private javax.swing.JButton UserPayBill;
    private javax.swing.JButton UserSend;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
